"""The published JSON Schema must say what pricing_validate.py says, and nothing else.

Standard library only for everything that matters here. The equivalence checks need a
JSON Schema implementation, which this repository does not depend on, so they skip
where it is absent and run in CI where it is installed -- see the `schema` job in
tests.yml.

Deliberately NOT named by any refresh workflow. A schema artifact that has drifted
from the validator is a real problem and a red build, but it says nothing about
whether a price was read correctly, and letting it stop the weekly publication would
repeat the mistake of gating a refresh on something unrelated to its own figures.
"""

from __future__ import annotations

import copy
import importlib.util
import json
import sys
import unittest
from pathlib import Path
from typing import Any, Callable

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))
sys.path.insert(0, str(REPO_ROOT))

import build_schema  # noqa: E402
import pricing_validate as validate  # noqa: E402
from pricing_validate import JSONDict  # noqa: E402
from tests.published import published_file  # noqa: E402

SCHEMA_PATH = REPO_ROOT / "pricing.schema.json"

# Asked rather than imported-and-caught: binding the module to None on failure makes
# every later `jsonschema.X` an attribute access on None, which is exactly what a type
# checker should complain about. The classes that need it import it where they use it.
HAS_JSONSCHEMA = importlib.util.find_spec("jsonschema") is not None
NEEDS_JSONSCHEMA = unittest.skipUnless(HAS_JSONSCHEMA, "jsonschema is not installed here")


class TestTheArtifactIsGenerated(unittest.TestCase):
    """The single rule that makes publishing a second description of the contract
    safe. Two hand-maintained definitions of one contract drift, and a schema that
    has drifted lies to consumers -- which is worse than publishing none."""

    def test_the_committed_schema_is_what_the_validator_describes(self) -> None:
        self.assertEqual(
            SCHEMA_PATH.read_text(encoding="utf-8"),
            build_schema.render(),
            "pricing.schema.json no longer matches pricing_validate.py. Run "
            "scripts/build_schema.py and commit the result; do not edit the schema.",
        )

    def test_the_check_flag_agrees(self) -> None:
        """The same comparison the CI job runs, so a green test means a green job."""
        self.assertEqual(build_schema.main(["--check"]), 0)

    def test_it_says_it_is_generated(self) -> None:
        """A reader who edits it by hand loses the edit on the next generate, so the
        file has to say so where they will see it."""
        schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
        self.assertIn("do not edit this file by hand", schema["description"])

    def test_it_names_what_it_cannot_check(self) -> None:
        """Without this, "it validates" reads as "it is sane", and a consumer trusts a
        figure that moved by a factor of a thousand overnight."""
        schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
        for missing in ("factor of", "api_ids", "currency"):
            self.assertIn(missing, schema["description"])

    def test_the_version_travels_with_the_file(self) -> None:
        schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
        self.assertEqual(
            schema["properties"]["schema_version"]["const"], validate.SCHEMA_VERSION
        )

    def test_every_known_price_field_is_described(self) -> None:
        """A field the validator accepts and the schema does not would make the
        published file fail its own published schema."""
        schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
        described = schema["$defs"]["entry"]["properties"]
        for field in validate.KNOWN_PRICE_FIELDS:
            with self.subTest(field=field):
                self.assertIn(field, described)
        for field in validate.NON_PRICE_ENTRY_FIELDS:
            with self.subTest(field=field):
                self.assertIn(field, described)

    def test_each_price_field_carries_the_bounds_that_unit_is_judged_by(self) -> None:
        """PRICE_BOUNDS exists because a plausible range is a statement about a unit.
        A schema that flattened them all to one range would reject real audio prices."""
        schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
        described = schema["$defs"]["entry"]["properties"]
        for field in validate.KNOWN_PRICE_FIELDS:
            low, high = validate.PRICE_BOUNDS.get(
                field, (validate.MIN_PLAUSIBLE, validate.MAX_PLAUSIBLE)
            )
            with self.subTest(field=field):
                self.assertEqual(described[field]["minimum"], low)
                self.assertEqual(described[field]["maximum"], high)


@NEEDS_JSONSCHEMA
class TestTheSchemaIsUsable(unittest.TestCase):
    def schema(self) -> JSONDict:
        return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))

    def test_it_is_itself_a_valid_json_schema(self) -> None:
        import jsonschema

        jsonschema.Draft202012Validator.check_schema(self.schema())

    def test_the_published_file_satisfies_it(self) -> None:
        """The point of the artifact. A consumer fetching both must be able to use one
        against the other."""
        import jsonschema

        doc = json.loads(published_file().read_text(encoding="utf-8"))
        errors = sorted(
            jsonschema.Draft202012Validator(self.schema()).iter_errors(doc),
            key=lambda e: list(e.path),
        )
        self.assertEqual(
            [],
            ["/".join(str(p) for p in e.path) + ": " + e.message for e in errors],
        )


@NEEDS_JSONSCHEMA
class TestTheSchemaRefusesWhatTheValidatorRefuses(unittest.TestCase):
    """A schema that accepts everything is worse than no schema: it hands a consumer
    a false assurance. Every case below is a document the Python validator rejects,
    and the schema must reject it too -- otherwise the two disagree about the contract
    and the published one is the weaker.
    """

    @classmethod
    def setUpClass(cls) -> None:
        cls.base = json.loads(published_file().read_text(encoding="utf-8"))

    def entries(self, doc: JSONDict) -> dict[str, Any]:
        return doc["providers"]["huggingface"]["models"]

    def first(self, doc: JSONDict) -> JSONDict:
        return next(iter(self.entries(doc).values()))

    def unpriced(self, doc: JSONDict) -> JSONDict:
        return next(e for e in self.entries(doc).values() if "unpriced_since" in e)

    def both_refuse(self, break_it: Callable[[JSONDict], None]) -> None:
        import jsonschema

        doc = copy.deepcopy(self.base)
        break_it(doc)
        with self.assertRaises(validate.ValidationError):
            validate.validate_document(doc)
        errors = list(jsonschema.Draft202012Validator(
            json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
        ).iter_errors(doc))
        self.assertTrue(errors, "the Python validator refuses this and the schema does not")

    def test_an_unknown_field(self) -> None:
        self.both_refuse(lambda d: self.first(d).update(per_banana=1.0))

    def test_free_and_priced_at_once(self) -> None:
        self.both_refuse(lambda d: self.first(d).update(free=True))

    def test_free_and_unpriced_at_once(self) -> None:
        self.both_refuse(lambda d: self.unpriced(d).update(free=True))

    def test_neither_a_price_nor_a_reason(self) -> None:
        self.both_refuse(lambda d: self.unpriced(d).pop("unpriced_since"))

    def test_a_price_of_zero(self) -> None:
        """The one this repository cares about most: 0 is what a broken parser reads,
        and it would tell a consumer the model is free."""
        self.both_refuse(lambda d: self.first(d).update(in_per_mtok=0))

    def test_an_implausible_price(self) -> None:
        self.both_refuse(lambda d: self.first(d).update(in_per_mtok=1_000_000))

    def test_free_written_as_false(self) -> None:
        self.both_refuse(lambda d: self.first(d).update(free=False))

    def test_an_unknown_kind(self) -> None:
        self.both_refuse(lambda d: self.first(d).update(kind="widget"))

    def test_a_marker_that_is_not_a_day(self) -> None:
        self.both_refuse(lambda d: self.unpriced(d).update(unpriced_since="yesterday"))

    def test_a_repeated_api_id(self) -> None:
        self.both_refuse(lambda d: self.first(d).update(api_ids=["a", "a"]))

    def test_a_generic_price_field(self) -> None:
        self.both_refuse(lambda d: self.first(d).update(price=1.0))

    def test_an_empty_display_name(self) -> None:
        self.both_refuse(lambda d: self.first(d).update(display_name=""))

    def test_a_schema_version_from_the_future(self) -> None:
        self.both_refuse(lambda d: d.update(schema_version=validate.SCHEMA_VERSION + 1))

    def test_sources_written_as_a_bare_string(self) -> None:
        self.both_refuse(
            lambda d: d["providers"]["mistral"].update(sources="https://example.invalid")
        )

    def test_a_timestamp_that_is_not_a_utc_stamp(self) -> None:
        self.both_refuse(
            lambda d: d["providers"]["ovh"].update(checked_utc="2026-09-14 12:00:00")
        )


if __name__ == "__main__":
    unittest.main()
